#!/bin/sh

. /lib/functions.sh

case "$ACTION" in
released)
	if [ "$SEEN" -lt 3 ]
	then
		/sbin/vpnonoff
	elif [ "$SEEN" -gt 3 ]
	then
		MODEL=`cat /proc/cpuinfo | grep machine | sed 's/^[^:]*:[ ]*// ; s/TP-LINK[ ]*//'`
		if [ "$MODEL" = "TL-MR3020" ];
		then
			/sbin/reboot
		else
			/sbin/wifionoff
		fi
	fi
;;
esac

return 0
