#!/bin/sh

. /lib/functions.sh

case "$ACTION" in
released)
	MODEL=`cat /proc/cpuinfo | grep machine | sed 's/^[^:]*:[ ]*// ; s/TP-LINK[ ]*// ; s/ .*//'`
	if [ "$SEEN" -lt 3 ]
	then
		/sbin/vpnonoff
	elif [ "$SEEN" -gt 3 ]
	then
		if [ "$MODEL" = "TL-MR3020" -o "$MODEL" = "TL-WR902AC" ];
		then
			echo "REBOOT" > /dev/console
			sync
			reboot
		else
			/sbin/wifionoff
		fi
	elif [ "$SEEN" -gt 10 ]
	then
		if [ "$MODEL" = "TL-MR3020" -o "$MODEL" = "TL-WR902AC" ];
                then
                        echo "FACTORY RESET" > /dev/console
        	        sync
	                file=factory /usr/share/cgi-bin/_set_system_config.sh
                else
			echo "REBOOT" > /dev/console
                        sync
			reboot
                fi
	fi
;;
esac

return 0
