#!/bin/bash
# usage: mkbuf file_to_make path_to_structured
cd $2
date "+%Y-%m-%d" > version
tar czf ../"$1".tmp *
cd ..
cat "$1".tmp | openssl enc -e -aes-256-cbc -pass pass:OurHardWorkByTheseWordsGuarded.PleaseDoNotSteal. > "$1".buf
# rm "$1".tmp
