#!/bin/sh
echo VPN stopping...
killall startingvpn 2> /dev/null
killall stoppingvpn 2> /dev/null
killall errorvpn 2> /dev/null
QSSled="/sys/class/leds/tp-link:green:qss"
echo none > $QSSled/trigger
echo 0 > $QSSled/brightness
