#!/bin/sh
VPNLED=none
[ -e "/sys/class/leds/tp-link:green:3g" ] && VPNLED="/sys/class/leds/tp-link:green:3g"
[ -e "/sys/class/leds/tp-link:green:wps" ] && VPNLED="/sys/class/leds/tp-link:green:wps"
[ -e "/sys/class/leds/tp-link:green:qss" ] && VPNLED="/sys/class/leds/tp-link:green:qss"
[ -e "/sys/class/leds/tl-wr902ac-v1:green:wps" ] && VPNLED="/sys/class/leds/tl-wr902ac-v1:green:wps"
echo "$VPNLED"
