#!/bin/sh
echo VPN deinitializing...
killall startingvpn 2> /dev/null
killall errorvpn 2> /dev/null
QSSled=`/etc/openvpn/led`                 
if [ "$QSSled" != "none" ];
 then
  echo none > $QSSled/trigger
  echo timer > $QSSled/trigger
  echo 700 > $QSSled/delay_on
  echo 400 > $QSSled/delay_off
fi
sleep 60
/etc/openvpn/errorvpn
