#!/bin/sh
echo VPN starting...
killall startingvpn 2> /dev/null
killall stoppingvpn 2> /dev/null
killall errorvpn 2> /dev/null
QSSled="/sys/class/leds/tp-link:green:qss"
echo none > $QSSled/trigger
echo 1 > $QSSled/brightness
