#!/bin/sh
DIS=`uci show wireless | grep "disabled.*1" | sed 's/wireless\.//' | sed 's/\.disabled.*//'`
ENA=`uci show wireless | grep "disabled.*0" | sed 's/wireless\.//' | sed 's/\.disabled.*//'`

for dev in $DIS;
do
 uci set wireless.$dev.disabled=0 ;
done
for dev in $ENA;
do
 uci set wireless.$dev.disabled=1 ;
done
uci commit

for dev in $DIS;
do
 wifi up $dev ;
done
for dev in $ENA;
do
 wifi down $dev ;
done
